jobs:
- job:
  displayName: macOS-10.13

  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: 'Add conda to PATH'

  - script: |
      conda config --system --set always_yes yes --set changeps1 no
      conda config --system --append channels conda-forge
      conda install -n base conda-devenv conda=4.6.14
    displayName: 'Configuring conda'

  - script: |
      conda devenv
    displayName: 'Running conda devenv'

  - script: |
      mkdir build ; cd build ; cmake ../ ; cmake --build . --target install --config Release
    displayName: 'Build and Install'

  - script: |
      source activate gibbs-py$(py_version)
      pytest --cov-config=.coveragerc --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html --cov=gibbs
      cd notebooks
      pytest --nbval
    displayName: 'Tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
