jobs:
- job:
  displayName: Windows vs2017

  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      conda config --system --set always_yes yes --set changeps1 no
      conda config --system --append channels conda-forge
      conda install -n base conda-devenv
    displayName: 'Configuring conda'

  - script: |
      conda devenv
    displayName: 'Running conda devenv'

  - script: |
      call activate gibbs-py$(py_version)
      pytest
      cd $(GIBBS_NOTEBOOKS_DIR)
      pytest --nbval
    displayName: 'Tests'
